### YamlMime:ManagedReference
items:
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration
  commentId: T:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration
  id: EmittedStream.WriterConfiguration
  parent: EventStore.Projections.Core.Services.Processing
  children:
  - EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.#ctor(EventStore.Projections.Core.Services.Processing.IEmittedStreamsWriter,EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata,IPrincipal,System.Int32,EventStore.Common.Log.ILogger)
  - EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Logger
  - EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxAge
  - EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxCount
  - EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxWriteBatchLength
  - EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.WriteAs
  - EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Writer
  langs:
  - csharp
  - vb
  name: EmittedStream.WriterConfiguration
  nameWithType: EmittedStream.WriterConfiguration
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration
  type: Class
  source:
    id: WriterConfiguration
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 68
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: 'public class WriterConfiguration : object'
    content.vb: >-
      Public Class WriterConfiguration
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.#ctor(EventStore.Projections.Core.Services.Processing.IEmittedStreamsWriter,EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata,IPrincipal,System.Int32,EventStore.Common.Log.ILogger)
  commentId: M:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.#ctor(EventStore.Projections.Core.Services.Processing.IEmittedStreamsWriter,EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata,IPrincipal,System.Int32,EventStore.Common.Log.ILogger)
  id: '#ctor(EventStore.Projections.Core.Services.Processing.IEmittedStreamsWriter,EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata,IPrincipal,System.Int32,EventStore.Common.Log.ILogger)'
  parent: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration
  langs:
  - csharp
  - vb
  name: WriterConfiguration(IEmittedStreamsWriter, EmittedStream.WriterConfiguration.StreamMetadata, IPrincipal, Int32, ILogger)
  nameWithType: EmittedStream.WriterConfiguration.WriterConfiguration(IEmittedStreamsWriter, EmittedStream.WriterConfiguration.StreamMetadata, IPrincipal, Int32, ILogger)
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.WriterConfiguration(EventStore.Projections.Core.Services.Processing.IEmittedStreamsWriter, EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata, IPrincipal, System.Int32, EventStore.Common.Log.ILogger)
  type: Constructor
  source:
    id: .ctor
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 96
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public WriterConfiguration(IEmittedStreamsWriter writer, EmittedStream.WriterConfiguration.StreamMetadata streamMetadata, IPrincipal writeAs, int maxWriteBatchLength, ILogger logger = null)
    parameters:
    - id: writer
      type: EventStore.Projections.Core.Services.Processing.IEmittedStreamsWriter
    - id: streamMetadata
      type: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata
    - id: writeAs
      type: IPrincipal
    - id: maxWriteBatchLength
      type: System.Int32
    - id: logger
      type: EventStore.Common.Log.ILogger
    content.vb: Public Sub New(writer As IEmittedStreamsWriter, streamMetadata As EmittedStream.WriterConfiguration.StreamMetadata, writeAs As IPrincipal, maxWriteBatchLength As Integer, logger As ILogger = Nothing)
  overload: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.WriteAs
  commentId: P:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.WriteAs
  id: WriteAs
  parent: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration
  langs:
  - csharp
  - vb
  name: WriteAs
  nameWithType: EmittedStream.WriterConfiguration.WriteAs
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.WriteAs
  type: Property
  source:
    id: WriteAs
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 109
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public IPrincipal WriteAs { get; }
    parameters: []
    return:
      type: IPrincipal
    content.vb: Public ReadOnly Property WriteAs As IPrincipal
  overload: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.WriteAs*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxWriteBatchLength
  commentId: P:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxWriteBatchLength
  id: MaxWriteBatchLength
  parent: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration
  langs:
  - csharp
  - vb
  name: MaxWriteBatchLength
  nameWithType: EmittedStream.WriterConfiguration.MaxWriteBatchLength
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxWriteBatchLength
  type: Property
  source:
    id: MaxWriteBatchLength
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 113
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public int MaxWriteBatchLength { get; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public ReadOnly Property MaxWriteBatchLength As Integer
  overload: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxWriteBatchLength*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Logger
  commentId: P:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Logger
  id: Logger
  parent: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration
  langs:
  - csharp
  - vb
  name: Logger
  nameWithType: EmittedStream.WriterConfiguration.Logger
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Logger
  type: Property
  source:
    id: Logger
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 117
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public ILogger Logger { get; }
    parameters: []
    return:
      type: EventStore.Common.Log.ILogger
    content.vb: Public ReadOnly Property Logger As ILogger
  overload: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Logger*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxCount
  commentId: P:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxCount
  id: MaxCount
  parent: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration
  langs:
  - csharp
  - vb
  name: MaxCount
  nameWithType: EmittedStream.WriterConfiguration.MaxCount
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxCount
  type: Property
  source:
    id: MaxCount
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 121
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public int? MaxCount { get; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Public ReadOnly Property MaxCount As Integer?
  overload: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxCount*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxAge
  commentId: P:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxAge
  id: MaxAge
  parent: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration
  langs:
  - csharp
  - vb
  name: MaxAge
  nameWithType: EmittedStream.WriterConfiguration.MaxAge
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxAge
  type: Property
  source:
    id: MaxAge
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 125
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public TimeSpan? MaxAge { get; }
    parameters: []
    return:
      type: System.Nullable{TimeSpan}
    content.vb: Public ReadOnly Property MaxAge As TimeSpan?
  overload: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxAge*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Writer
  commentId: P:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Writer
  id: Writer
  parent: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration
  langs:
  - csharp
  - vb
  name: Writer
  nameWithType: EmittedStream.WriterConfiguration.Writer
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Writer
  type: Property
  source:
    id: Writer
    path: /Users/chrisward/Workspace/EventStore/EventStore/src/EventStore.Projections.Core/Services/Processing/EmittedStream.cs
    startLine: 129
  assemblies:
  - EventStore.Projections.Core
  namespace: EventStore.Projections.Core.Services.Processing
  syntax:
    content: public IEmittedStreamsWriter Writer { get; }
    parameters: []
    return:
      type: EventStore.Projections.Core.Services.Processing.IEmittedStreamsWriter
    content.vb: Public ReadOnly Property Writer As IEmittedStreamsWriter
  overload: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Writer*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: EventStore.Projections.Core.Services.Processing
  commentId: N:EventStore.Projections.Core.Services.Processing
  name: EventStore.Projections.Core.Services.Processing
  nameWithType: EventStore.Projections.Core.Services.Processing
  fullName: EventStore.Projections.Core.Services.Processing
- uid: System.Object
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.#ctor*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.#ctor
  name: WriterConfiguration
  nameWithType: EmittedStream.WriterConfiguration.WriterConfiguration
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.WriterConfiguration
- uid: EventStore.Projections.Core.Services.Processing.IEmittedStreamsWriter
  commentId: T:EventStore.Projections.Core.Services.Processing.IEmittedStreamsWriter
  parent: EventStore.Projections.Core.Services.Processing
  name: IEmittedStreamsWriter
  nameWithType: IEmittedStreamsWriter
  fullName: EventStore.Projections.Core.Services.Processing.IEmittedStreamsWriter
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata
  commentId: T:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata
  parent: EventStore.Projections.Core.Services.Processing
  name: EmittedStream.WriterConfiguration.StreamMetadata
  nameWithType: EmittedStream.WriterConfiguration.StreamMetadata
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.StreamMetadata
- uid: IPrincipal
  isExternal: true
  name: IPrincipal
  nameWithType: IPrincipal
  fullName: IPrincipal
- uid: System.Int32
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: EventStore.Common.Log.ILogger
  commentId: T:EventStore.Common.Log.ILogger
  parent: EventStore.Common.Log
  name: ILogger
  nameWithType: ILogger
  fullName: EventStore.Common.Log.ILogger
- uid: EventStore.Common.Log
  commentId: N:EventStore.Common.Log
  name: EventStore.Common.Log
  nameWithType: EventStore.Common.Log
  fullName: EventStore.Common.Log
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.WriteAs*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.WriteAs
  name: WriteAs
  nameWithType: EmittedStream.WriterConfiguration.WriteAs
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.WriteAs
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxWriteBatchLength*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxWriteBatchLength
  name: MaxWriteBatchLength
  nameWithType: EmittedStream.WriterConfiguration.MaxWriteBatchLength
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxWriteBatchLength
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Logger*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Logger
  name: Logger
  nameWithType: EmittedStream.WriterConfiguration.Logger
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Logger
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxCount*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxCount
  name: MaxCount
  nameWithType: EmittedStream.WriterConfiguration.MaxCount
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxCount
- uid: System.Nullable{System.Int32}
  commentId: '!:System.Nullable{System.Int32}'
  definition: System.Nullable`1
  name: Nullable<Int32>
  nameWithType: Nullable<Int32>
  fullName: System.Nullable<System.Int32>
  nameWithType.vb: Nullable(Of Int32)
  fullName.vb: System.Nullable(Of System.Int32)
  name.vb: Nullable(Of Int32)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Int32
    name: Int32
    nameWithType: Int32
    fullName: System.Int32
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  isExternal: true
  name: Nullable<>
  nameWithType: Nullable<>
  fullName: System.Nullable<>
  nameWithType.vb: Nullable(Of )
  fullName.vb: System.Nullable(Of )
  name.vb: Nullable(Of )
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxAge*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxAge
  name: MaxAge
  nameWithType: EmittedStream.WriterConfiguration.MaxAge
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.MaxAge
- uid: System.Nullable{TimeSpan}
  commentId: '!:System.Nullable{TimeSpan}'
  definition: System.Nullable`1
  name: Nullable<TimeSpan>
  nameWithType: Nullable<TimeSpan>
  fullName: System.Nullable<TimeSpan>
  nameWithType.vb: Nullable(Of TimeSpan)
  fullName.vb: System.Nullable(Of TimeSpan)
  name.vb: Nullable(Of TimeSpan)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: TimeSpan
    name: TimeSpan
    nameWithType: TimeSpan
    fullName: TimeSpan
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: TimeSpan
    name: TimeSpan
    nameWithType: TimeSpan
    fullName: TimeSpan
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Writer*
  commentId: Overload:EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Writer
  name: Writer
  nameWithType: EmittedStream.WriterConfiguration.Writer
  fullName: EventStore.Projections.Core.Services.Processing.EmittedStream.WriterConfiguration.Writer
